modLoader="kotlinforforge"
loaderVersion="*"
license='MIT'

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="skyevg"
authors="skyevg"
description='''
Open a LAN server to anyone, anywhere, anytime.
'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${mc_version == "1.19.4" ? "[1.19,)" : "[1.18,1.19)"}"
ordering="NONE"
side="BOTH"
